CREATE ROLE web_anon NOLOGIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO web_anon;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO web_anon;


ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON tables TO web_anon;
